IF ("${REPOSITORY_NAME}" STREQUAL "")
  SET(REPOSITORY_NAME JSON)
ENDIF()

SET(${REPOSITORY_NAME}_VERSION 1.0)
SET(${REPOSITORY_NAME}_MAJOR_VERSION 01)
SET(${REPOSITORY_NAME}_MAJOR_MINOR_VERSION 010000)
SET(${REPOSITORY_NAME}_VERSION_STRING "1.0")
SET(${REPOSITORY_NAME}_ENABLE_DEVELOPMENT_MODE_DEFAULT OFF) # Change to 'OFF' for a release
